name: Unit tests

on:
  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]

env:
  CC: clang
  CXX: clang++
  
jobs:
  unit_tests:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/picsart/luabind:main
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      options: --user root

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Configure
      run: cmake --preset=luabind -DCODE_COVERAGE=ON
    - name: Build
      run: cmake --build --preset=luabind --target all
    - name: Unit tests
      run: ctest --preset=unit_tests

    - name: Collect coverage
      run: lcov --directory . --capture  --include '*/luabind/include/*'  --output-file coverage.info
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

