name: Unit tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CC: clang
  CXX: clang++
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Prerequisites
      run: apt-get -q update -y && \
           apt-get -q install -y --no-install-recommends \
           ninja-build

    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Configure
      run: cmake --preset=luabind
    - name: Build
      run: cmake --build --preset=luabind --target all
    - name: Unit tests
      run: ctest --preset=unit_tests

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

