name: Unit tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CC: clang
  CXX: clang++
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Configure
      run: cmake --preset=luabind -G="Unix Makefiles"
    - name: Build
      run: cmake --build --preset=luabind --target all
    - name: Unit tests
      run: ctest --preset=unit_tests
